name = "CeterisParibus"
uuid = "a57bfac2-9dcb-4f10-991f-84e7ca4a5e8e"
authors = ["Aru Bhardwaj <aruecon@gmail.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
